// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hggdgcbrdanwmlbgeaca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnZ2RnY2JyZGFud21sYmdlYWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMjk1NTMsImV4cCI6MjA3NzkwNTU1M30.YJzZkScbJ5IYX1t8EcQ5WTc08RdeQ_z97oGundg9byY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});